[book]
authors = ["babar contributors"]
language = "en"
src = "docs"
title = "The Book of Babar"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/notthatbreezy/babar"
site-url = "https://babar.notthatbreezy.io/"
