//! Procedural macros for the `babar` PostgreSQL driver.
//!
//! The main entry points are [`sql!`](macro@sql), [`query!`](macro@query),
//! [`command!`](macro@command), and the `#[derive(Codec)]` derive, all
//! re-exported from the `babar` crate.

use proc_macro::TokenStream;
use std::collections::{HashMap, HashSet};

use proc_macro2::TokenTree as TokenTree2;
use quote::{format_ident, quote};
use syn::parse::{Parse, ParseStream};
use syn::{
    parse_macro_input, Attribute, Data, DeriveInput, Expr, ExprMacro, Field, Fields,
    GenericArgument, Generics, Ident, LitStr, PathArguments, Result, Token, Type, TypePath,
};
use verify::{parse_declared_types, verify_param_metadata, verify_statement_against_probe, Probe};

#[allow(dead_code)]
mod schema_decl;
#[allow(dead_code)]
mod typed_sql;
#[allow(dead_code)]
mod verify;

mod kw {
    syn::custom_keyword!(params);
    syn::custom_keyword!(row);
}

struct SqlInput {
    sql: LitStr,
    bindings: Vec<Binding>,
}

struct Binding {
    name: Ident,
    expr: Expr,
}

struct CompiledSql {
    sql: String,
    codecs: Vec<Expr>,
}

#[allow(dead_code)]
struct QueryInput {
    sql: LitStr,
    params: Expr,
    row: Expr,
}

#[allow(dead_code)]
struct CommandInput {
    sql: LitStr,
    params: Expr,
}

impl Parse for SqlInput {
    fn parse(input: ParseStream<'_>) -> Result<Self> {
        let sql = input.parse()?;
        let mut bindings = Vec::new();

        if input.is_empty() {
            return Ok(Self { sql, bindings });
        }

        input.parse::<Token![,]>()?;
        while !input.is_empty() {
            let name = input.parse()?;
            input.parse::<Token![=]>()?;
            let expr = input.parse()?;
            bindings.push(Binding { name, expr });
            if input.is_empty() {
                break;
            }
            input.parse::<Token![,]>()?;
        }

        Ok(Self { sql, bindings })
    }
}

impl Parse for QueryInput {
    fn parse(input: ParseStream<'_>) -> Result<Self> {
        let sql = input.parse()?;
        input.parse::<Token![,]>()?;
        input.parse::<kw::params>()?;
        input.parse::<Token![=]>()?;
        let params = input.parse()?;
        input.parse::<Token![,]>()?;
        input.parse::<kw::row>()?;
        input.parse::<Token![=]>()?;
        let row = input.parse()?;
        if !input.is_empty() {
            input.parse::<Token![,]>()?;
        }
        if !input.is_empty() {
            return Err(input.error("unexpected trailing tokens in query!"));
        }
        Ok(Self { sql, params, row })
    }
}

impl Parse for CommandInput {
    fn parse(input: ParseStream<'_>) -> Result<Self> {
        let sql = input.parse()?;
        input.parse::<Token![,]>()?;
        input.parse::<kw::params>()?;
        input.parse::<Token![=]>()?;
        let params = input.parse()?;
        if !input.is_empty() {
            input.parse::<Token![,]>()?;
        }
        if !input.is_empty() {
            return Err(input.error("unexpected trailing tokens in command!"));
        }
        Ok(Self { sql, params })
    }
}

/// Build a `babar::query::Fragment` from SQL that uses named placeholders.
///
/// When `BABAR_DATABASE_URL` or `DATABASE_URL` is set during macro expansion,
/// the macro best-effort verifies parameter metadata against a live PostgreSQL
/// server if every binding codec is in the v1 verifiable subset (`int2`,
/// `int4`, `int8`, `bool`, `text`, `varchar`, `bytea`, `nullable(...)`, and
/// tuples of those). Unsupported binding codecs fall back to the normal
/// expansion path. v0.1 does not provide an offline verification cache.
#[proc_macro]
pub fn sql(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as SqlInput);
    match compile_input(&input) {
        Ok(compiled) => {
            if let Err(err) = verify_sql_input(&input, &compiled) {
                return err.into_compile_error().into();
            }
            let sql = LitStr::new(&compiled.sql, input.sql.span());
            let codecs = compiled.codecs;
            let n_params = codecs.len();
            quote! {{
                ::babar::query::Fragment::__from_parts(
                    #sql,
                    (#(#codecs,)*),
                    #n_params,
                    ::core::option::Option::Some(::babar::query::Origin::new(
                        file!(),
                        line!(),
                        column!(),
                    )),
                )
            }}
            .into()
        }
        Err(err) => err.into_compile_error().into(),
    }
}

/// Build a schema-aware typed `babar::query::Query`.
///
/// Public `query!` now routes through babar's unified schema-aware typed SQL
/// compiler. Calls must provide schema facts up front with `schema = { ... }`,
/// or use a schema-scoped wrapper generated by [`schema!`].
#[proc_macro]
pub fn query(input: TokenStream) -> TokenStream {
    expand_public_typed_macro::<QueryInput>(
        input,
        "query",
        "`query!(\"...\", params = ..., row = ...)`",
    )
}

/// Build a schema-aware typed command statement.
///
/// Public `command!` now routes through babar's unified schema-aware typed SQL
/// compiler. Non-`RETURNING` write statements stay command-style/no-row, while
/// explicit `RETURNING` statements lower through the row-returning query path.
#[proc_macro]
pub fn command(input: TokenStream) -> TokenStream {
    expand_public_typed_macro::<CommandInput>(input, "command", "`command!(\"...\", params = ...)`")
}

/// Declare an authored schema module with reusable table and column symbols.
///
/// The v0.1 surface is intentionally small:
///
/// - `schema! { pub mod app_schema { table public.users { id: primary_key(int4) } } }`
/// - one schema module can contain multiple `table` declarations
/// - field markers currently support `nullable(...)`, `primary_key(...)`, and
///   `pk(...)`
/// - SQL type names match the inline `query!` / `command!` schema type surface
///
/// The generated module exposes one nested module per table with `TABLE`,
/// per-column symbols, authored declaration metadata through `SCHEMA`, and
/// schema-scoped `query!` / `command!` wrappers that reuse the authored tables.
/// Tables with unique names remain available as `app_schema::users`, while
/// same-name tables from different SQL schemas are namespaced like
/// `app_schema::public::users` and `app_schema::reporting::users`.
#[proc_macro]
pub fn schema(input: TokenStream) -> TokenStream {
    schema_decl::expand_schema(input)
}

fn expand_public_typed_macro<T: Parse>(
    input: TokenStream,
    macro_name: &str,
    legacy_example: &str,
) -> TokenStream {
    let tokens = proc_macro2::TokenStream::from(input.clone());
    let inline_example = match macro_name {
        "query" => "SELECT ...",
        "command" => "INSERT/UPDATE/DELETE ...",
        _ => "SELECT ...",
    };
    let schema_wrapper = match macro_name {
        "query" => "app_schema::query!(...)",
        "command" => "app_schema::command!(...)",
        _ => "app_schema::query!(...)",
    };
    if syn::parse2::<T>(tokens.clone()).is_ok() {
        return public_macro_error(
            &tokens,
            format!(
                "`{macro_name}!` no longer accepts the old explicit-codec form {legacy_example}; \
use schema-aware typed SQL (`{macro_name}!(schema = {{ ... }}, {inline_example})`) or an authored \
schema wrapper like `{schema_wrapper}`. For unsupported statements, use `Query::raw` / \
`Command::raw`."
            ),
        );
    }

    match first_ident(&tokens).as_deref() {
        Some("schema") | Some("__babar_schema") => match macro_name {
            "query" => typed_sql::expand_query(input),
            "command" => typed_sql::expand_command(input),
            _ => unreachable!("unsupported public typed SQL macro"),
        },
        _ => public_macro_error(
            &tokens,
            format!(
                "`{macro_name}!` now expects schema-aware typed SQL. Start with `schema = {{ ... }}` \
for inline examples/tests, or use a schema-scoped wrapper like `{schema_wrapper}`. Use \
`Query::raw` / `Command::raw` for explicit raw fallbacks."
            ),
        ),
    }
}

fn public_macro_error(tokens: &proc_macro2::TokenStream, message: String) -> TokenStream {
    let span = tokens
        .clone()
        .into_iter()
        .next()
        .map(|token| token.span())
        .unwrap_or_else(proc_macro2::Span::call_site);
    syn::Error::new(span, message).into_compile_error().into()
}

fn first_ident(tokens: &proc_macro2::TokenStream) -> Option<String> {
    match tokens.clone().into_iter().next() {
        Some(TokenTree2::Ident(ident)) => Some(ident.to_string()),
        _ => None,
    }
}

fn verify_sql_input(input: &SqlInput, compiled: &CompiledSql) -> Result<()> {
    let Some(expected) = verifiable_param_types(&compiled.codecs) else {
        return Ok(());
    };

    let Some(probe) = Probe::discover().map_err(|err| syn::Error::new(input.sql.span(), err))?
    else {
        return Ok(());
    };

    let statement = probe
        .describe(&compiled.sql)
        .map_err(|err| syn::Error::new(input.sql.span(), err))?;
    verify_param_metadata(&statement.params, &expected)
        .map_err(|err| syn::Error::new(input.sql.span(), err))
}

#[allow(dead_code)]
fn compile_query_input(input: &QueryInput) -> Result<proc_macro2::TokenStream> {
    let sql_value = input.sql.value();
    let params = parse_declared_types(&input.params).map_err(|err| err.into_syn_error())?;
    let row = parse_declared_types(&input.row).map_err(|err| err.into_syn_error())?;
    verify_statement_against_probe(&sql_value, &params, Some(&row))
        .map_err(|err| syn::Error::new(input.sql.span(), err))?;

    let sql = LitStr::new(&sql_value, input.sql.span());
    let params_expr = compile_codec_dsl_expr(&input.params)?;
    let row_expr = compile_codec_dsl_expr(&input.row)?;
    let n_params = params.len();

    Ok(quote! {{
        let __babar_fragment = ::babar::query::Fragment::__from_parts(
            #sql,
            #params_expr,
            #n_params,
            ::core::option::Option::Some(::babar::query::Origin::new(
                file!(),
                line!(),
                column!(),
            )),
        );
        ::babar::query::Query::from_fragment(__babar_fragment, #row_expr)
    }})
}

#[allow(dead_code)]
fn compile_command_input(input: &CommandInput) -> Result<proc_macro2::TokenStream> {
    let sql_value = input.sql.value();
    let params = parse_declared_types(&input.params).map_err(|err| err.into_syn_error())?;
    verify_statement_against_probe(&sql_value, &params, None)
        .map_err(|err| syn::Error::new(input.sql.span(), err))?;

    let sql = LitStr::new(&sql_value, input.sql.span());
    let params_expr = compile_codec_dsl_expr(&input.params)?;
    let n_params = params.len();

    Ok(quote! {{
        let __babar_fragment = ::babar::query::Fragment::__from_parts(
            #sql,
            #params_expr,
            #n_params,
            ::core::option::Option::Some(::babar::query::Origin::new(
                file!(),
                line!(),
                column!(),
            )),
        );
        ::babar::query::Command::from_fragment(__babar_fragment)
    }})
}

fn verifiable_param_types(codecs: &[Expr]) -> Option<Vec<verify::DeclaredType>> {
    let mut types = Vec::new();
    for codec in codecs {
        let declared = parse_declared_types(codec).ok()?;
        types.extend(declared);
    }
    Some(types)
}

#[allow(dead_code)]
fn compile_codec_dsl_expr(expr: &Expr) -> Result<proc_macro2::TokenStream> {
    if let Expr::Tuple(tuple) = strip_expr(expr) {
        let mut codecs = Vec::new();
        for elem in &tuple.elems {
            flatten_codec_dsl(elem, &mut codecs)?;
        }
        return Ok(quote! { (#(#codecs,)*) });
    }

    let mut codecs = Vec::new();
    flatten_codec_dsl(expr, &mut codecs)?;
    Ok(match codecs.as_slice() {
        [] => quote! { () },
        [codec] => quote! { #codec },
        _ => quote! { (#(#codecs,)*) },
    })
}

#[allow(dead_code)]
fn flatten_codec_dsl(expr: &Expr, codecs: &mut Vec<proc_macro2::TokenStream>) -> Result<()> {
    let expr = strip_expr(expr);
    match expr {
        Expr::Tuple(tuple) => {
            for elem in &tuple.elems {
                flatten_codec_dsl(elem, codecs)?;
            }
            Ok(())
        }
        _ => {
            codecs.push(compile_codec_dsl_scalar(expr)?);
            Ok(())
        }
    }
}

#[allow(dead_code)]
fn compile_codec_dsl_scalar(expr: &Expr) -> Result<proc_macro2::TokenStream> {
    let expr = strip_expr(expr);
    if let Some(path) = as_path(expr) {
        let Some(ident) = path.path.segments.last().map(|segment| &segment.ident) else {
            return Err(syn::Error::new_spanned(
                expr,
                "unsupported empty codec path in verifiable codec DSL",
            ));
        };
        return match ident.to_string().as_str() {
            "int2" | "int4" | "int8" | "bool" | "text" | "varchar" | "bytea" => {
                Ok(quote! { ::babar::codec::#ident })
            }
            _ => Err(syn::Error::new_spanned(
                expr,
                format!(
                    "unsupported verifiable codec `{ident}`; expected int2, int4, int8, bool, text, varchar, bytea, nullable(...), or tuples of these"
                ),
            )),
        };
    }

    let Expr::Call(call) = expr else {
        return Err(syn::Error::new_spanned(
            expr,
            "unsupported verifiable codec DSL; expected a codec path, nullable(...), or a tuple of these",
        ));
    };
    let Some(path) = as_path(&call.func) else {
        return Err(syn::Error::new_spanned(
            expr,
            "unsupported verifiable codec DSL; expected nullable(...) around a supported codec",
        ));
    };
    if path
        .path
        .segments
        .last()
        .is_none_or(|segment| segment.ident != "nullable")
    {
        return Err(syn::Error::new_spanned(
            expr,
            "unsupported verifiable codec call; only nullable(...) is supported",
        ));
    }
    if call.args.len() != 1 {
        return Err(syn::Error::new_spanned(
            expr,
            "nullable(...) in verifiable codec DSL must have exactly one argument",
        ));
    }

    let inner = compile_codec_dsl_scalar(call.args.first().expect("nullable args length checked"))?;
    Ok(quote! { ::babar::codec::nullable(#inner) })
}

/// Derive a `CODEC` associated constant for a named struct.
///
/// Fields infer default codecs for supported unambiguous Rust types. Use
/// `#[pg(codec = "...")]` to override inference or provide a codec for
/// unsupported types. The string is parsed as a Rust expression in a scope
/// that brings `babar::codec::*` into scope, so values like `"int4"`,
/// `"nullable(text)"`, or `"typed_json::<MyType>()"` all work.
///
/// ```ignore
/// use babar::query::Query;
///
/// #[derive(Debug, Clone, PartialEq, babar::Codec)]
/// struct UserRow {
///     id: i32,
///     email: String,
///     note: Option<String>,
///     #[pg(codec = "varchar")]
///     handle: String,
/// }
///
/// let _query: Query<(), UserRow> = Query::raw(
///     "SELECT id, email, note, handle FROM users",
///     (),
///     UserRow::CODEC,
/// );
/// ```
#[proc_macro_derive(Codec, attributes(pg))]
pub fn derive_codec(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match compile_codec_derive(&input) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.into_compile_error().into(),
    }
}

fn compile_input(input: &SqlInput) -> Result<CompiledSql> {
    let mut seen = HashSet::new();
    let mut bindings = HashMap::new();
    for binding in &input.bindings {
        let name = binding.name.to_string();
        if !seen.insert(name.clone()) {
            return Err(syn::Error::new(
                binding.name.span(),
                format!("duplicate sql! binding `{name}`"),
            ));
        }
        bindings.insert(name, binding);
    }

    let mut sql = String::with_capacity(input.sql.value().len());
    let mut codecs = Vec::new();
    let mut slots = HashMap::<String, usize>::new();
    let mut used = HashSet::<String>::new();
    let source = input.sql.value();
    let chars: Vec<char> = source.chars().collect();
    let mut i = 0;

    while i < chars.len() {
        if chars[i] == '$' && i + 1 < chars.len() && is_ident_start(chars[i + 1]) {
            let start = i + 1;
            i += 2;
            while i < chars.len() && is_ident_continue(chars[i]) {
                i += 1;
            }
            let name: String = chars[start..i].iter().collect();
            let Some(binding) = bindings.get(&name) else {
                return Err(syn::Error::new(
                    input.sql.span(),
                    format!("sql! placeholder `${name}` has no binding"),
                ));
            };
            used.insert(name.clone());

            if let Some(nested) = nested_sql(&binding.expr)? {
                let compiled = compile_input(&nested)?;
                renumber_into(&compiled.sql, codecs.len(), &mut sql);
                codecs.extend(compiled.codecs);
                continue;
            }

            let slot = *slots.entry(name).or_insert_with(|| {
                codecs.push(binding.expr.clone());
                codecs.len()
            });
            sql.push('$');
            sql.push_str(&slot.to_string());
            continue;
        }

        sql.push(chars[i]);
        i += 1;
    }

    for binding in &input.bindings {
        let name = binding.name.to_string();
        if !used.contains(&name) {
            return Err(syn::Error::new(
                binding.name.span(),
                format!("sql! binding `{name}` is unused"),
            ));
        }
    }

    Ok(CompiledSql { sql, codecs })
}

fn compile_codec_derive(input: &DeriveInput) -> Result<proc_macro2::TokenStream> {
    reject_generics(&input.generics)?;

    let ident = &input.ident;
    let data = match &input.data {
        Data::Struct(data) => data,
        _ => {
            return Err(syn::Error::new_spanned(
                input,
                "Codec can only be derived for structs",
            ))
        }
    };
    let fields = match &data.fields {
        Fields::Named(fields) => &fields.named,
        _ => {
            return Err(syn::Error::new_spanned(
                data.fields.clone(),
                "Codec requires a struct with named fields",
            ))
        }
    };

    let codec_ident = format_ident!("__Babar{}Codec", ident);
    let assert_ident = format_ident!("__babar_assert_field_codecs_for_{}", ident);
    let mut field_idents = Vec::new();
    let mut field_types = Vec::new();
    let mut codec_exprs = Vec::new();
    let mut decoded_idents = Vec::new();
    let mut assert_blocks = Vec::new();

    for (index, field) in fields.iter().enumerate() {
        let field_ident = field.ident.clone().expect("named field");
        let field_ty = field.ty.clone();
        let codec_expr = parse_codec_attr(field)?;
        let decoded_ident = format_ident!("__babar_field_{index}");

        let assert_block = quote! {
            {
                fn assert_codec<C>(_: &C)
                where
                    C: ::babar::codec::Encoder<#field_ty> + ::babar::codec::Decoder<#field_ty>,
                {}
                assert_codec(&{ use ::babar::codec::*; #codec_expr });
            }
        };

        field_idents.push(field_ident);
        field_types.push(field_ty);
        codec_exprs.push(codec_expr);
        decoded_idents.push(decoded_ident);
        assert_blocks.push(assert_block);
    }

    let tuple_type = quote! { (#(#field_types,)*) };
    let tuple_codec = quote! { (#({ use ::babar::codec::*; #codec_exprs },)*) };
    let encode_fields =
        field_idents
            .iter()
            .zip(codec_exprs.iter())
            .map(|(field_ident, codec_expr)| {
                quote! {
                    ::babar::codec::Encoder::encode(
                        &{ use ::babar::codec::*; #codec_expr },
                        &value.#field_ident,
                        params,
                    )?;
                }
            });

    let expanded = quote! {
        #[doc(hidden)]
        #[derive(Clone, Copy, Debug)]
        pub struct #codec_ident;

        #[doc(hidden)]
        #[allow(non_snake_case)]
        fn #assert_ident() {
            #(#assert_blocks)*
        }

        impl #ident {
            /// Codec generated by `#[derive(Codec)]` for this struct.
            pub const CODEC: #codec_ident = #codec_ident;
        }

        impl ::babar::codec::Encoder<#ident> for #codec_ident {
            fn encode(
                &self,
                value: &#ident,
                params: &mut ::std::vec::Vec<::core::option::Option<::std::vec::Vec<u8>>>,
            ) -> ::babar::Result<()> {
                #assert_ident();
                #(#encode_fields)*
                ::core::result::Result::Ok(())
            }

            fn oids(&self) -> &'static [::babar::types::Oid] {
                #assert_ident();
                let codec = #tuple_codec;
                <_ as ::babar::codec::Encoder<#tuple_type>>::oids(&codec)
            }

            fn format_codes(&self) -> &'static [i16] {
                #assert_ident();
                let codec = #tuple_codec;
                <_ as ::babar::codec::Encoder<#tuple_type>>::format_codes(&codec)
            }
        }

        impl ::babar::codec::Decoder<#ident> for #codec_ident {
            fn decode(&self, columns: &[::core::option::Option<::babar::__private::Bytes>]) -> ::babar::Result<#ident> {
                #assert_ident();
                let codec = #tuple_codec;
                let (#(#decoded_idents,)*) = <_ as ::babar::codec::Decoder<#tuple_type>>::decode(&codec, columns)?;
                ::core::result::Result::Ok(#ident { #(#field_idents: #decoded_idents,)* })
            }

            fn n_columns(&self) -> usize {
                #assert_ident();
                let codec = #tuple_codec;
                <_ as ::babar::codec::Decoder<#tuple_type>>::n_columns(&codec)
            }

            fn oids(&self) -> &'static [::babar::types::Oid] {
                #assert_ident();
                let codec = #tuple_codec;
                <_ as ::babar::codec::Decoder<#tuple_type>>::oids(&codec)
            }

            fn format_codes(&self) -> &'static [i16] {
                #assert_ident();
                let codec = #tuple_codec;
                <_ as ::babar::codec::Decoder<#tuple_type>>::format_codes(&codec)
            }
        }
    };

    Ok(expanded)
}

fn reject_generics(generics: &Generics) -> Result<()> {
    if generics.params.is_empty() {
        return Ok(());
    }
    Err(syn::Error::new_spanned(
        generics,
        "Codec derive does not support generic structs yet",
    ))
}

fn parse_codec_attr(field: &Field) -> Result<Expr> {
    let mut codec = None;
    for attr in &field.attrs {
        if !attr.path().is_ident("pg") {
            continue;
        }
        parse_pg_attr(attr, &mut codec)?;
    }

    codec.map_or_else(|| infer_field_codec(field), Ok)
}

fn parse_pg_attr(attr: &Attribute, codec: &mut Option<Expr>) -> Result<()> {
    attr.parse_nested_meta(|meta| {
        if !meta.path.is_ident("codec") {
            return Err(meta.error("unsupported #[pg(...)] attribute; expected codec = \"...\""));
        }
        if codec.is_some() {
            return Err(meta.error("duplicate codec attribute"));
        }
        let lit: LitStr = meta.value()?.parse()?;
        *codec = Some(lit.parse()?);
        Ok(())
    })
}

fn infer_field_codec(field: &Field) -> Result<Expr> {
    let Some(codec) = infer_codec_expr(&field.ty) else {
        let field_ty = &field.ty;
        return Err(syn::Error::new_spanned(
            field_ty,
            format!(
                "no default codec inference for field type `{}`; add #[pg(codec = \"...\")]",
                quote!(#field_ty)
            ),
        ));
    };
    syn::parse_str(&codec)
}

fn infer_codec_expr(ty: &Type) -> Option<String> {
    if type_matches(ty, &["i16"]) {
        return Some("int2".into());
    }
    if type_matches(ty, &["i32"]) {
        return Some("int4".into());
    }
    if type_matches(ty, &["i64"]) {
        return Some("int8".into());
    }
    if type_matches(ty, &["bool"]) {
        return Some("bool".into());
    }
    if type_matches(ty, &["String"])
        || type_matches(ty, &["std", "string", "String"])
        || type_matches(ty, &["alloc", "string", "String"])
    {
        return Some("text".into());
    }
    if let Some(inner) = generic_type_arg(ty, &["Option"])
        .or_else(|| generic_type_arg(ty, &["std", "option", "Option"]))
        .or_else(|| generic_type_arg(ty, &["core", "option", "Option"]))
    {
        return infer_codec_expr(inner).map(|codec| format!("nullable({codec})"));
    }
    if let Some(inner) = generic_type_arg(ty, &["Vec"])
        .or_else(|| generic_type_arg(ty, &["std", "vec", "Vec"]))
        .or_else(|| generic_type_arg(ty, &["alloc", "vec", "Vec"]))
    {
        if type_matches(inner, &["u8"]) {
            return Some("bytea".into());
        }
    }
    None
}

fn type_matches(ty: &Type, expected: &[&str]) -> bool {
    let Type::Path(TypePath { qself: None, path }) = ty else {
        return false;
    };
    let segments: Vec<_> = path
        .segments
        .iter()
        .map(|segment| segment.ident.to_string())
        .collect();
    segments
        .iter()
        .map(String::as_str)
        .eq(expected.iter().copied())
}

fn generic_type_arg<'a>(ty: &'a Type, expected: &[&str]) -> Option<&'a Type> {
    let Type::Path(TypePath { qself: None, path }) = ty else {
        return None;
    };
    if !path
        .segments
        .iter()
        .map(|segment| segment.ident.to_string())
        .collect::<Vec<_>>()
        .iter()
        .map(String::as_str)
        .eq(expected.iter().copied())
    {
        return None;
    }
    let last = path.segments.last()?;
    let PathArguments::AngleBracketed(args) = &last.arguments else {
        return None;
    };
    let mut type_args = args.args.iter().filter_map(|arg| {
        let GenericArgument::Type(ty) = arg else {
            return None;
        };
        Some(ty)
    });
    let first = type_args.next()?;
    if type_args.next().is_some() {
        return None;
    }
    Some(first)
}

fn nested_sql(expr: &Expr) -> Result<Option<SqlInput>> {
    let Expr::Macro(ExprMacro { mac, .. }) = expr else {
        return Ok(None);
    };
    if !path_ends_with_sql(&mac.path) {
        return Ok(None);
    }
    syn::parse2::<SqlInput>(mac.tokens.clone()).map(Some)
}

#[allow(dead_code)]
fn strip_expr(mut expr: &Expr) -> &Expr {
    loop {
        expr = match expr {
            Expr::Paren(paren) => &paren.expr,
            Expr::Group(group) => &group.expr,
            _ => return expr,
        };
    }
}

#[allow(dead_code)]
fn as_path(expr: &Expr) -> Option<&syn::ExprPath> {
    let Expr::Path(path) = strip_expr(expr) else {
        return None;
    };
    Some(path)
}

fn path_ends_with_sql(path: &syn::Path) -> bool {
    path.segments
        .last()
        .is_some_and(|segment| segment.ident == "sql")
}

fn is_ident_start(ch: char) -> bool {
    ch == '_' || ch.is_ascii_alphabetic()
}

fn is_ident_continue(ch: char) -> bool {
    ch == '_' || ch.is_ascii_alphanumeric()
}

fn renumber_into(sql: &str, offset: usize, out: &mut String) {
    if offset == 0 {
        out.push_str(sql);
        return;
    }

    let bytes = sql.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'$' && i + 1 < bytes.len() && bytes[i + 1].is_ascii_digit() {
            let mut j = i + 1;
            while j < bytes.len() && bytes[j].is_ascii_digit() {
                j += 1;
            }
            let slot = std::str::from_utf8(&bytes[i + 1..j])
                .expect("nested sql placeholder digits")
                .parse::<usize>()
                .expect("nested sql placeholder parses")
                + offset;
            out.push('$');
            out.push_str(&slot.to_string());
            i = j;
            continue;
        }

        out.push(bytes[i] as char);
        i += 1;
    }
}
